---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: quay.io/coreos/jsonnet-ci
  environment:
    BIN_DIR: ./tmp/bin
  commands:
  - find . -type f -not -path './vendor/*' \( -name '*.libsonnet' -o -name '*.jsonnet' \) | xargs -L1 jsonnetfmt --test
  - mkdir -p $${BIN_DIR} && curl -o $${BIN_DIR}/jb -L "https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v0.2.0/jb-$$(go env GOOS)-$$(go env GOARCH)"
  - chmod +x $${BIN_DIR}/jb && $${BIN_DIR}/jb install
  - ./build.sh
  - git diff --exit-code
