version: 1

validators:
  # ignore links for release tarballs
  - regex: 'releases\/download'
    type: 'ignore'
  # Always returns 403.
  - regex: 'cloudflare\.com'
    type: 'ignore'
  # May return a 404 in some environments
  - regex: 'twitter\.com'
    type: 'ignore'