version: 1

inputDir: "docs"
outputDir: "website/content/docs"

gitIgnored: true
localLinksStyle:
  hugo:
    indexFileName: "_index.md"

transformations:

  - glob: "README.md"
    path: _index.md
    popHeader: false
    frontMatter:
      template: | 
        title: "{{ .Origin.FirstHeader }}"
        lead: ""
        lastmod: "{{ .Origin.LastMod }}"
        images: []
        draft: false
        description: Documentation for Observatorium.
        date: "2021-04-30T10:40:00+00:00"

  - glob: "**/README.md"
    path: _index.md
    popHeader: true
    frontMatter:
      template: |
        title: "{{ .Origin.FirstHeader }}"
        lead: ""
        lastmod: "{{ .Origin.LastMod }}"
        images: []
        draft: false
        date: "2021-04-30T10:40:00+00:00"

  - glob: "usage/*.md"
    path: /usage/*
    popHeader: true
    frontMatter:
      template: |
        weight: 1
        toc: true
        title: "{{ .Origin.FirstHeader }}"
        menu:
            docs:
                parent: usage
        lead: ""
        lastmod: "{{ .Origin.LastMod }}"
        images: []
        draft: false
        description: ""
        date: "2021-04-30T10:40:00+00:00"

  - glob: "design/*.md"
    path: /design/*
    popHeader: true
    frontMatter:
      template: |
        weight: 10
        toc: true
        title: "{{ .Origin.FirstHeader }}"
        menu:
            docs:
                parent: design
        lead: ""
        lastmod: "{{ .Origin.LastMod }}"
        images: []
        draft: false
        description: ""
        date: "2021-04-30T10:40:00+00:00"

  - glob: "community/*.md"
    path: /community/*
    popHeader: true
    frontMatter:
      template: |
        weight: 10
        toc: true
        title: "{{ .Origin.FirstHeader }}"
        menu:
            docs:
                parent: community
        lead: ""
        lastmod: "{{ .Origin.LastMod }}"
        images: []
        draft: false
        description: ""
        date: "2021-04-30T10:40:00+00:00"
