apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: memcached
  name: memcached
  namespace: observatorium
spec:
  clusterIP: None
  ports:
  - name: memcached
    port: 11211
    targetPort: 11211
  selector:
    app.kubernetes.io/name: memcached
