apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: observatorium-api-thanos-querier
  name: observatorium-api-thanos-querier
  namespace: observatorium
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: observatorium-api-thanos-querier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: observatorium-api-thanos-querier
        app.kubernetes.io/tracing: jaeger-agent
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - observatorium-api-thanos-querier
              namespaces:
              - observatorium
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - query
        - --query.replica-label=replica
        - --query.replica-label=ruler_replica
        - --query.replica-label=prometheus_replica
        - --web.external-prefix=/ui/v1/metrics
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --store=dnssrv+_grpc._tcp.thanos-store.observatorium.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-ruler.observatorium.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-receive-default.observatorium.svc.cluster.local
        image: quay.io/thanos/thanos:v0.9.0
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          periodSeconds: 30
        name: observatorium-api-thanos-querier
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 9090
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      terminationGracePeriodSeconds: 120
