apiVersion: v1
data:
  authorize_url: ""
  client_id: ""
  client_secret: ""
  oidc_issuer: ""
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-server
  name: telemeter-server
  namespace: observatorium
type: Opaque
