apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/part-of: observatorium
  name: observatorium-xyz-thanos
  namespace: observatorium
