apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: master-2020-10-23-v0.1.1-180-g7c57706
  name: observatorium-xyz-observatorium-api
  namespace: observatorium
