apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: rate-limiter
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: gubernator
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 0.9.1
  name: observatorium-xyz-gubernator
  namespace: observatorium
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: grpc
    port: 81
    targetPort: 81
  selector:
    app.kubernetes.io/component: rate-limiter
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: gubernator
    app.kubernetes.io/part-of: observatorium
