apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: tracing
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: observatorium
  name: observatorium-xyz-jaeger-query
  namespace: observatorium
spec:
  ports:
  - name: query
    port: 16686
    targetPort: 16686
  selector:
    app.kubernetes.io/component: tracing
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: observatorium
