apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: tracing
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: observatorium
  name: observatorium-xyz-jaeger-collector-headless
  namespace: observatorium
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 14250
    targetPort: 14250
  selector:
    app.kubernetes.io/component: tracing
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: observatorium
