version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run: make fmt
      - run: make generate configuration/tests/manifests
      - run: |
          git diff --exit-code -- . \
            ':(exclude)configuration/tests/manifests/observatorium-xyz-tls-secret.yaml' \
            ':(exclude)configuration/tests/manifests/observatorium-xyz-tls-configmap.yaml' \
            ':(exclude)configuration/tests/manifests/observatorium-xyz-tls-dex.yaml' \
            ':(exclude)configuration/tests/manifests/test-ca-tls.yaml' \
            ':(exclude).bingo/*'
      - run: make validate

  tests:
    machine: true
    steps:
      - checkout
      - run:
          name: e2e tests
          no_output_timeout: 30m
          command : |
            ./configuration/tests/e2e.sh kind
            ./configuration/tests/e2e.sh deploy
            ./configuration/tests/e2e.sh test
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  test-and-push:
    jobs:
      - build
      - tests
