jobs:
  build:
    working_directory: /go/src/github.com/observatorium/deployments
    docker:
      - image: quay.io/coreos/jsonnet-ci
    steps:
      - checkout
      - run: find . -type f -not -path './*vendor/*' \( -name '*.libsonnet' -o -name '*.jsonnet' \) | xargs -L1 jsonnetfmt --test
      - run: make vendor-jsonnet
      - run: make environments/base/manifests environments/dev/manifests example/manifests tests/manifests
      - run: git diff --exit-code

  tests:
    machine: true
    steps:
      - checkout
      - run: |
          ./tests/e2e.sh kind
          ./tests/e2e.sh deploy
          ./tests/e2e.sh test

  test-operator:
    machine: true
    steps:
      - checkout
      - run: |
          ./tests/e2e.sh kind
          ./tests/e2e.sh deploy-operator
          ./tests/e2e.sh test
          ./tests/e2e.sh delete-cr

  container-push:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login quay.io --username $DOCKER_USER --password-stdin
          make container-push

workflows:
  version: 2
  tagged-master:
    jobs:
      - container-push:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
  test-and-push:
    jobs:
      - build
      - tests
      - test-operator
      - container-push:
          requires:
            - build
          filters:
            branches:
              only:
                - master
