apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rate-limiter
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: gubernator
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 0.9.1
  name: observatorium-xyz-gubernator
  namespace: observatorium
