apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: compactor
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 2.8.0
  name: observatorium-xyz-loki-compactor
  namespace: observatorium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: compactor
      app.kubernetes.io/instance: observatorium-xyz
      app.kubernetes.io/name: loki
      app.kubernetes.io/part-of: observatorium
  serviceName: observatorium-xyz-loki-compactor
  template:
    metadata:
      labels:
        app.kubernetes.io/component: compactor
        app.kubernetes.io/instance: observatorium-xyz
        app.kubernetes.io/name: loki
        app.kubernetes.io/part-of: observatorium
    spec:
      containers:
      - args:
        - -target=compactor
        - -config.file=/etc/loki/config/config.yaml
        - -limits.per-user-override-config=/etc/loki/config/overrides.yaml
        - -config.expand-env=true
        env:
        - name: LOKI_LOG_LEVEL
          value: info
        - name: LOKI_REPLICATION_FACTOR
          value: "1"
        - name: LOKI_QUERIER_MAX_CONCURRENCY
          value: "2"
        - name: LOKI_INGESTER_WAL_REPLAY_MEMORY_CEILING
          value: 100MB
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: loki-objectstorage
        image: docker.io/grafana/loki:2.8.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /metrics
            port: 3100
            scheme: HTTP
          periodSeconds: 30
        name: observatorium-xyz-loki-compactor
        ports:
        - containerPort: 3100
          name: metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/loki/config/
          name: config
          readOnly: false
        - mountPath: /data
          name: storage
          readOnly: false
      volumes:
      - configMap:
          name: observatorium-xyz-loki
        name: config
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/instance: observatorium-xyz
        app.kubernetes.io/name: loki
        app.kubernetes.io/part-of: observatorium
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 250Mi
