apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: observatorium-jaeger-collector
spec:
  endpoints:
  - port: admin-http
  namespaceSelector:
    matchNames:
    - '{{namespace}}'
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-all-in-one
