apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: observatorium-jaeger-agent
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - telemeter-production
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-agent
