apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: app-sre
  name: observatorium-jaeger-agent
spec:
  namespaceSelector:
    matchNames:
    - telemeter-stage
  podMetricsEndpoints:
  - targetPort: 14271
  selector:
    matchLabels:
      app.kubernetes.io/tracing: jaeger-agent
