apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: prometheus-ams
spec:
  endpoints:
  - interval: 30s
    port: web
  namespaceSelector:
    matchNames:
    - '{{namespace}}'
  selector:
    matchLabels:
      app.kubernetes.io/instance: ams
      app.kubernetes.io/name: prometheus
