apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: prometheus-ams-production
  namespace: ${NAMESPACE}
spec:
  endpoints:
  - interval: 30s
    port: web
  namespaceSelector:
    matchNames:
    - telemeter-production
  selector:
    matchLabels:
      prometheus: ams
