apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: thanos-receive
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchLabels:
    - telemeter-stage
  selector:
    matchLabels:
      app: thanos-receive
