apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: main-2022-03-03-v0.1.2-139-gb3a1918
  name: observatorium-xyz-observatorium-api
  namespace: observatorium
spec:
  ports:
  - name: internal
    port: 8081
    targetPort: 8081
  - name: public
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
