apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: main-2022-11-14-v0.1.2-283-gc29a861
  name: observatorium-xyz-observatorium-api
  namespace: observatorium
