apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: ruler
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: 2.7.2
  name: observatorium-xyz-loki-ruler
  namespace: observatorium
spec:
  ports:
  - name: ruler-http-metrics
    port: 3100
    targetPort: 3100
  - name: ruler-grpc
    port: 9095
    targetPort: 9095
  selector:
    app.kubernetes.io/component: ruler
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observatorium
