---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    containerImage: quay.io/observatorium/observatorium-operator:latest
  name: observatorium-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Observatorium
      displayName: Observatorium
      kind: Observatorium
      name: observatoria.core.observatorium.io
      version: v1alpha1
  description: |2-

    Observatorium Operator provides the ability to install the components that comprise the Observatorium project.
  displayName: Observatorium Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - core.observatorium.io
          resources:
          - observatoria
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - core.observatorium.io
          resources:
          - observatoria/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - create
          - get
          - patch
          - update
          - list
          - watch
          - delete
        - apiGroups:
          - apps
          resources:
          - statefulsets
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - services
          - services/finalizers
          - endpoints
          verbs:
          - get
          - create
          - update
          - delete
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - '*'
        serviceAccountName: observatorium-operator
      deployments:
      - name: observatorium-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: observatorium-operator
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: observatorium-operator
            spec:
              containers:
              - args:
                - --log-level=debug
                image: quay.io/observatorium/observatorium-operator:latest
                imagePullPolicy: IfNotPresent
                name: observatorium-operator
                resources:
                  limits:
                    cpu: 100m
                    memory: 600Mi
                  requests:
                    cpu: 100m
                    memory: 600Mi
              serviceAccountName: observatorium-operator
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - observatorium-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        serviceAccountName: observatorium-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - observatorium
  - prometheus
  - thanos
  links:
  - name: Source Code
    url: https://github.com/observatorium/configuration
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
